/** Carrusel del banner — máx. 3 slides según minuta YAAVS */
window.YAAVS_HERO_CAROUSEL = {
  interval: 7000,
  transitionMs: 1400,
  mobileBreakpoint: "(max-width: 768px)",
  slideDefaults: {
    objectFit: "cover",
    objectPosition: "center center",
    objectFitMobile: "cover",
    objectPositionMobile: "center top",
    widthMobile: 1080,
    heightMobile: 2400,
  },
  images: [
    {
      videoBanner: true,
      videoSrc: "assets/hero-telecom/banners/dili-dili-dili.mp4",
      videoSrcMobile: "assets/hero-telecom/banners/dili-dili-dili.mp4",
      src: "assets/hero-telecom/banners/banner-horizontal-poster.jpg",
      srcMobile: "assets/hero-telecom/banners/banner-vertical-poster.jpg",
      width: 1920,
      height: 1080,
      widthMobile: 1080,
      heightMobile: 1920,
      objectFit: "cover",
      objectPosition: "center center",
      objectFitMobile: "cover",
      objectPositionMobile: "center center",
      alt: "YAAVS — Dili Dili Dili.",
      hidePromo: true,
      duration: 0,
    },
    {
      /* Desktop banner (mesa de trabajo 5yaav2web) */
      src: "assets/hero-telecom/mesa-trabajo-5yaav2web.png",
      srcMobile: "assets/hero-telecom/mesa-trabajo-5yaav2web.png",
      width: 2400,
      height: 1080,
      widthMobile: 2400,
      heightMobile: 1080,
      objectFit: "cover",
      objectPosition: "center center",
      objectFitMobile: "cover",
      objectPositionMobile: "center center",
      alt: "YAAVS — distribución nacional de SIMs y telecom en México.",
      hidePromo: true,
    },
    {
      src: "assets/yaavser/cliente-satisfecho.jpg",
      srcMobile: "assets/yaavser/cliente-satisfecho.jpg",
      width: 1920,
      height: 1080,
      widthMobile: 1080,
      heightMobile: 1350,
      objectFit: "cover",
      objectPosition: "center center",
      objectFitMobile: "cover",
      objectPositionMobile: "center center",
      alt: "Socio comercial YAAVS en su punto de venta.",
      promo: {
        badge: "Red nacional",
        kicker: "Únete a la red",
        title: "¿Conviértete en",
        accent: "Yaavser?",
        lead: "Afíliate con respaldo comercial, visitas en tu zona, rotulación y capacitación para vender más en tu mostrador.",
        cta: "Quiero ser Yaavser",
        href: "ser-yaavser.html",
      },
    },
  ],
  fallback: "assets/hero-bg.svg",
};
