/** Carrusel del banner — máx. 3 slides según minuta YAAVS */
window.YAAVS_HERO_CAROUSEL = {
  interval: 7000,
  transitionMs: 1400,
  mobileBreakpoint: "(max-width: 768px)",
  slideDefaults: {
    objectFit: "cover",
    objectPosition: "center center",
    objectFitMobile: "cover",
    objectPositionMobile: "center top",
    widthMobile: 1080,
    heightMobile: 2400,
  },
  images: [
    {
      src: "assets/yaavstys/yaavstys-3.png",
      srcMobile: "assets/yaavstys/yaavstys-3.png",
      width: 1200,
      height: 1200,
      widthMobile: 1080,
      heightMobile: 1080,
      objectFit: "contain",
      objectPosition: "center bottom",
      objectFitMobile: "contain",
      objectPositionMobile: "center bottom",
      alt: "YAAVS — líder en distribución de SIM's en México.",
      promo: {
        badge: "Grupo YAAVS",
        kicker: "¿Quiénes somos?",
        title: "Líder en distribución",
        accent: "de SIM's",
        lead: "Somos el distribuidor nacional de chips, recargas y conectividad que impulsa a miles de socios comerciales.",
        cta: "Conoce más",
        href: "quienes-somos.html",
      },
    },
    {
      src: "assets/yaavser/cliente-satisfecho.jpg",
      srcMobile: "assets/yaavser/cliente-satisfecho.jpg",
      width: 1920,
      height: 1080,
      widthMobile: 1080,
      heightMobile: 1350,
      objectFit: "cover",
      objectPosition: "center center",
      objectFitMobile: "cover",
      objectPositionMobile: "center center",
      alt: "Socio comercial YAAVS en su punto de venta.",
      promo: {
        badge: "Red nacional",
        kicker: "Únete a la red",
        title: "¿Conviértete en",
        accent: "Yaavser?",
        lead: "Afíliate con respaldo comercial, visitas en tu zona, rotulación y capacitación para vender más en tu mostrador.",
        cta: "Quiero ser Yaavser",
        href: "ser-yaavser.html",
      },
    },
    {
      src: "assets/hero-telecom/hero-telecom-2.jpg",
      srcMobile: "assets/hero-telecom/mobile/hero-telecom-2.jpg",
      widthMobile: 1080,
      heightMobile: 2400,
      objectPositionMobile: "center top",
      alt: "Unidades de negocio del Grupo YAAVS.",
      promo: {
        badge: "Ecosistema YAAVS",
        kicker: "Prepago · Pospago · Academia · YAASHOP",
        title: "Unidades de",
        accent: "negocio",
        lead: "Todas las líneas del grupo en un solo sitio: venta prepago y postpago, capacitación y retail.",
        cta: "Ver prepago y pospago",
        href: "#plan-picker",
      },
    },
  ],
  fallback: "assets/hero-bg.svg",
};
