/** Carrusel del banner — máx. 3 slides según minuta YAAVS */
window.YAAVS_HERO_CAROUSEL = {
  interval: 7000,
  transitionMs: 1400,
  mobileBreakpoint: "(max-width: 768px)",
  slideDefaults: {
    objectFit: "cover",
    objectPosition: "center center",
    objectFitMobile: "cover",
    objectPositionMobile: "center top",
    widthMobile: 1080,
    heightMobile: 2400,
  },
  images: [
    {
      videoBanner: true,
      videoSrc: "assets/hero-telecom/banners/dili-dili-dili.mp4",
      videoSrcMobile: "assets/hero-telecom/banners/dili-dili-dili.mp4",
      src: "assets/hero-telecom/banners/quienes-map-poster.jpg",
      srcMobile: "assets/hero-telecom/banners/quienes-map-poster-vertical.jpg",
      width: 1920,
      height: 1080,
      widthMobile: 1080,
      heightMobile: 1920,
      objectFit: "cover",
      objectPosition: "center center",
      objectFitMobile: "cover",
      objectPositionMobile: "center center",
      alt: "YAAVS — ¿Quiénes somos?",
      duration: 0,
      promo: {
        title: "¿Quiénes",
        accent: "somos?",
        lead: "Líder distribuidor de SIMs. Conectividad a +16,000 negocios en México.",
        cta: "Conócenos",
        href: "quienes-somos.html",
      },
    },
    {
      /* Desktop: servicios horizontal · Móvil: servicios vertical */
      videoBanner: true,
      videoSrc: "assets/hero-telecom/banners/servicios-h-20260804.mp4",
      videoSrcMobile: "assets/hero-telecom/banners/servicios-v-20260804.mp4",
      src: "assets/hero-telecom/banners/servicios-h-20260804-poster.jpg",
      srcMobile: "assets/hero-telecom/banners/servicios-v-20260804-poster.jpg",
      width: 1920,
      height: 1080,
      widthMobile: 1080,
      heightMobile: 1920,
      objectFit: "cover",
      objectPosition: "center center",
      objectFitMobile: "cover",
      objectPositionMobile: "center center",
      alt: "YAAVS — conoce nuestros servicios.",
      duration: 0,
      promo: {
        title: "Conoce",
        accent: "nuestros servicios",
        lead: "",
        cta: "Ver servicios",
        href: "#servicios-preview",
      },
    },
    {
      /* Desktop: 3.mp4 · Móvil: 3.5.mp4 */
      videoBanner: true,
      videoSrc: "assets/hero-telecom/banners/3.mp4",
      videoSrcMobile: "assets/hero-telecom/banners/3.5.mp4",
      src: "assets/hero-telecom/banners/3-poster.jpg",
      srcMobile: "assets/hero-telecom/banners/3.5-poster.jpg",
      width: 1920,
      height: 1080,
      widthMobile: 1080,
      heightMobile: 1920,
      objectFit: "cover",
      objectPosition: "center center",
      objectFitMobile: "cover",
      objectPositionMobile: "center center",
      alt: "Conviértete en socio comercial — red nacional YAAVS.",
      duration: 0,
      promo: {
        title: "Conviértete en",
        accent: "socio comercial",
        lead: "",
        cta: "Únete como socio",
        href: "#",
        openLead: true,
      },
    },
  ],
  fallback: "assets/hero-bg.svg",
};
